# Data path. adjust them!
common:
    image_file:  "/home/squirtle/Desktop/Squirtle/cv/ws_livox/data/basic1_and_advance4_calibration/image/0.png"
    from_bag: false   # if true, use rosbag to generate pcd file, then use them to calibrate, else use pcd file directly
    pcd_file:  "/home/squirtle/Desktop/Squirtle/cv/ws_livox/data/basic1_and_advance4_calibration/pcd/0.pcd"
    bag_file:  "/home/squirtle/Desktop/Squirtle/cv/ws_livox/data/basic1_and_advance4_calibration/livox_bag/0.bag"
    save_pcd_file:  "/home/squirtle/Desktop/Squirtle/cv/ws_livox/data/basic1_and_advance4_calibration/my_pcd/0.pcd"
    result_file: "/home/squirtle/Desktop/Squirtle/cv/ws_livox/data/basic1_and_advance4_calibration/extrinsic_single_calib.txt"

# Camera Parameters. Adjust them!
camera:
    camera_matrix:  [910.623, 0.0, 651.66,
                     0.0,  910.183, 365.568,
                     0.0, 0.0, 1.0 ] 
    dist_coeffs: [0.0, 0.0, 0.0, 0.0, 0.0]

# Calibration Parameters.!
calib:
    calib_config_file: "/home/squirtle/Desktop/Squirtle/cv/ws_livox/src/livox_camera_calib/config/config_indoor.yaml"
    use_rough_calib: true # set true if your initial_extrinsic is bad
